### PR TITLE
Task(05_HTML): add praktikum, screenshot, and summary

### PR DESCRIPTION
**Pull request by hariefairuzzaki**
Task 05_HTML

1. [x] praktikum: index.html, form.html, welcome.html
2. [x] screenshot
3. [x] summary

### CODE REVIEW

**Comment by syukronarie** [comment]
Halo @hariefairuzzaki

Commit terakhirmu d530c918397ae458969f2af15e16062caab566f5 delete 05_HTML jadi terhapuslah tasks HTMLmu, kamu push lagi tasks HTML nya dg commit baru

**Review by syukronarie — COMMENTED** [review]
Push lagi tasks HTML nya bro @hariefairuzzaki

**Comment by hariefairuzzaki** [comment]
> Halo @hariefairuzzaki
> 
> Commit terakhirmu [d530c91](https://github.com/hariefairuzzaki/react_harie-fairuzzaki/commit/d530c918397ae458969f2af15e16062caab566f5) delete 05_HTML jadi terhapuslah tasks HTMLmu, kamu push lagi tasks HTML nya dg commit baru

> itu ngehapus 05_HTML yang di branch 'main' mas, soalnya tadi ga ke trigger buat PR baru

**Comment by hariefairuzzaki** [comment]
> > Halo @hariefairuzzaki
> > Commit terakhirmu [d530c91](https://github.com/hariefairuzzaki/react_harie-fairuzzaki/commit/d530c918397ae458969f2af15e16062caab566f5) delete 05_HTML jadi terhapuslah tasks HTMLmu, kamu push lagi tasks HTML nya dg commit baru
> 
> > itu ngehapus 05_HTML yang di branch 'main' mas, soalnya tadi ga ke trigger buat PR baru

> commit nya yang ini mas 0dca03d071100c679bace0dae60dacc9928c8d73

**Comment by syukronarie** [comment]
> > Halo @hariefairuzzaki
> > Commit terakhirmu [d530c91](https://github.com/hariefairuzzaki/react_harie-fairuzzaki/commit/d530c918397ae458969f2af15e16062caab566f5) delete 05_HTML jadi terhapuslah tasks HTMLmu, kamu push lagi tasks HTML nya dg commit baru
> 
> > itu ngehapus 05_HTML yang di branch 'main' mas, soalnya tadi ga ke trigger buat PR baru

jadi mau di approve dulu ini?
dan buat PR baru lagi?

**Review by syukronarie — APPROVED** [review]
Ok. Reviewed. Tolong perbaiki ya issuenya lalu buat PR baru. Tks

**Comment by hariefairuzzaki** [comment]
> > > Halo @hariefairuzzaki
> > > Commit terakhirmu [d530c91](https://github.com/hariefairuzzaki/react_harie-fairuzzaki/commit/d530c918397ae458969f2af15e16062caab566f5) delete 05_HTML jadi terhapuslah tasks HTMLmu, kamu push lagi tasks HTML nya dg commit baru
> > 
> > 
> > > itu ngehapus 05_HTML yang di branch 'main' mas, soalnya tadi ga ke trigger buat PR baru
> 
> jadi mau di approve dulu ini? dan buat PR baru lagi?

iya mas, mungkin boleh di approve dulu

**Pull request merged**
