### PR TITLE
Task(05_HTML): Add praktikum, screenshot, and summary

### PR DESCRIPTION
**Pull request by hariefairuzzaki**
Task:
1. [x] praktikum: index.html, form.html, welcome.html
2. [x] screenshot
3. [x] summary

### CODE REVIEW

**Review by syukronarie — COMMENTED** [review]
Hi @hariefairuzzaki,

mana tasks HTML nya?

**Comment by hariefairuzzaki** [comment]
> Hi @hariefairuzzaki,
> 
> 
> 
> mana tasks HTML nya?

di folder praktikum mas

**Comment by syukronarie** [comment]
> > Hi @hariefairuzzaki,
> > mana tasks HTML nya?
> 
> di folder praktikum mas

Di sini ya
- Tasks [d7ca976](https://github.com/hariefairuzzaki/react_harie-fairuzzaki/commit/d7ca9767077c8dea181eefc5d62c42774c9a39d6)
- SS & Summary [164ee73](https://github.com/hariefairuzzaki/react_harie-fairuzzaki/commit/164ee7382356dcb455229aaad36cbe59cda30db6)

**Review by syukronarie — APPROVED** [review]
Approved

**Pull request merged**
